//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public int codDepto { get; set; }
        public string nombreDpto { get; set; }
        public string ciudad { get; set; }
        public string director { get; set; }
    }
}
