//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int nDIEmp { get; set; }
        public string nombEmp { get; set; }
        public string sexEmp { get; set; }
        public System.DateTime fecNac { get; set; }
        public System.DateTime fecIncorporacion { get; set; }
        public int salEmp { get; set; }
        public int comis { get; set; }
        public int codSuc { get; set; }
        public int jefeDI { get; set; }
        public string cargo { get; set; }
        public int nroDepto { get; set; }
    }
}
